spring.datasource.url=jdbc:h2:mem:hospitalopd
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.thymeleaf.cache=false

app.security.admin.username=admin
app.security.admin.password=admin123
app.security.reception.username=reception
app.security.reception.password=reception123
app.security.nurse.username=nurse
app.security.nurse.password=nurse123
app.security.doctor.username=doctor
app.security.doctor.password=doctor123
